/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sign;


import Model.Doctorant;
import Model.Enseignant;
import javax.swing.JOptionPane;
import java.sql.* ;
import java.sql.PreparedStatement ;
import Model.sqlConnection ;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author oouak
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public LOGIN() {
        initComponents();
        String filename ="C:\\Users\\oouak\\Pictures\\icon.png";
        filename=filename.replace('\\','/');
        ImageIcon img = new ImageIcon(filename);
        this.setIconImage(img.getImage());
        this.setTitle("Authentification");
        //setExtendedState(JFrame.MAXIMIZED BOTH);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        left_background = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        right_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        email.setBackground(new java.awt.Color(0, 153, 204));
        email.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        email.setOpaque(false);
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 490, 50));

        password.setBackground(new java.awt.Color(0, 153, 204));
        password.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 500, 50));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\oouak\\Documents\\NetBeansProjects\\Cedoc\\src\\main\\java\\Icons\\icon1.png")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 440, 50, 40));

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 120, 40));

        jButton2.setBackground(new java.awt.Color(0, 51, 102));
        jButton2.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 440, 100, 40));

        jButton3.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jButton3.setText("Register");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 500, 240, 40));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\oouak\\Pictures\\logo cedocc.png")); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 500, 530, 100));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Centre de Gestion de CEDOC");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, -10, 520, 120));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\oouak\\Documents\\NetBeansProjects\\Cedoc\\src\\main\\java\\Icons\\icons8_education_60px.png")); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 110, 50));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 23)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Excellence Since 1992");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, 570, 100));

        left_background.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        left_background.setForeground(new java.awt.Color(204, 0, 51));
        left_background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        left_background.setIcon(new javax.swing.ImageIcon("C:\\Users\\oouak\\Pictures\\sign in.png")); // NOI18N
        jPanel2.add(left_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 600));

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email");
        jLabel4.setToolTipText("");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 120, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Password");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 110, 50));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\oouak\\Documents\\NetBeansProjects\\Cedoc\\src\\main\\java\\Icons\\icons8_collaborator_male_64px_1.png")); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 60, 60));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\oouak\\Documents\\NetBeansProjects\\Cedoc\\src\\main\\java\\Icons\\icons8_password_window_48px.png")); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 70, 60));

        jCheckBox1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox1.setText("Doctorant ");
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 394, -1, 30));

        jCheckBox2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox2.setText("Enseignant");
        jPanel2.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 444, -1, 30));

        right_background.setBackground(new java.awt.Color(0, 153, 204));
        right_background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        right_background.setOpaque(true);
        jPanel2.add(right_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, -60, 560, 740));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // REGISTRATION BUTTON 
        //JOptionPane.showMessageDialog(null,"Not yet ready !");
        new Registration2().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // CODE HERE FOR LOG IN BOUTTON
        try{
            Connection con =sqlConnection.dbconnection();
            // il faut separer la connexion de doctorant de celle de l'enseignant 
            //apres la connexion de l'enseignant on affiche la dashboard que j'ai designé 
            //pour la connexion doctorant on afffiche celle de mohamed
            String sql="" ;
            if (jCheckBox1.isSelected()){ // Doctorant
                sql= "select * from info_etudiant where email=? ";
                PreparedStatement st=con.prepareStatement(sql);
		st.setString(1,email.getText());
		ResultSet rst=st.executeQuery();
		while(rst.next()) {
                    if(password.getText().equals(rst.getString(3))) {
			JOptionPane.showMessageDialog(null, "logged in");
			dispose();
			Acceuil home = new Acceuil(rst.getInt(1));
			home.setVisible(true);
			break;
			}
                    else {
			JOptionPane.showMessageDialog(null, "wrong password or username");
			password.setText("");
			}
		}

                
            }
            if (jCheckBox2.isSelected()){ // Enseignant
                sql = "Select * from info_ens where email=?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1,email.getText());
                //pst.setString(2,password.getText());    
                ResultSet rs = pst.executeQuery();
                if(rs.next()){
                    if (rs.getString("Password").equals(password.getText())){
            
                        System.out.println(rs.getString("email"));
                        System.out.println(rs.getString("prenom"));
                
                        JOptionPane.showMessageDialog(null,"Email and Password Matched ");
               
                
                        Enseignant user = new Enseignant(rs.getInt("id"),rs.getString("Nom"),rs.getString("Prenom"),rs.getString("email"),rs.getString("CIN"),rs.getString("Password"),rs.getString("specialite"),rs.getInt("tel"),rs.getString("departement"),rs.getString("Picture"));
                        new Dashboard_enseignant(user.Nom ,user.Prenom,user.CIN,user.Email,user.Password,user.Image,user.ID,user.departement,user.Specialite,user.Telephone).setVisible(true);
                
                        this.setVisible(false);
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Usename and Password Doesnt Match ");   
                        email.setText(""); 
                        password.setText("");
                
                    }
                }
            }
           
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
           
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel left_background;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel right_background;
    // End of variables declaration//GEN-END:variables
}
